public enum mg_pr_EResourceList
{
	TITLE_ASSET_BACKGROUND,
	GAME_ASSET_BACKGROUND,
	GAME_ASSET_PUFFLE_BLACK,
	GAME_ASSET_PUFFLE_BLUE,
	GAME_ASSET_PUFFLE_BROWN,
	GAME_ASSET_PUFFLE_GREEN,
	GAME_ASSET_PUFFLE_ORANGE,
	GAME_ASSET_PUFFLE_PINK,
	GAME_ASSET_PUFFLE_PURPLE,
	GAME_ASSET_PUFFLE_RED,
	GAME_ASSET_PUFFLE_WHITE,
	GAME_ASSET_PUFFLE_YELLOW,
	GAME_ASSET_OBSTICLE_ROCK1,
	GAME_ASSET_OBSTICLE_ROCK2,
	GAME_ASSET_OBSTICLE_STUMP
}
