namespace ClubPenguin.ClothingDesigner.ItemCustomizer
{
	public enum AreaTouchedEnum
	{
		INVENTORY_BUTTON,
		PENGUIN_PREVIEW_ROTATION_AREA,
		RED_CHANNEL,
		GREEN_CHANNEL,
		BLUE_CHANNEL,
		TEMPLATE_BUTTON,
		DECAL_BUTTON,
		FABRIC_BUTTON,
		CLICK_BLOCKING_UI,
		PENGUIN_ROTATION_AREA,
		NOTHING
	}
}
