namespace ClubPenguin.Diving
{
	public enum ChomperState
	{
		NONE,
		IDLE,
		HUNGRY,
		LUNGE,
		LUNGE_SUCCESS,
		LUNGE_SUCCESS_SPIT_WAIT,
		LUNGE_SUCCESS_SPIT_COMPLETE,
		LUNGE_SUCCESS_ANIMATION_WAIT,
		LUNGE_SUCCESS_ANIMATION_COMPLETE,
		LUNGE_MISS,
		LUNGE_MISS_ANIMATION_WAIT,
		LUNGE_MISS_ANIMATION_COMPLETE,
		REVIVE_PAUSE_WAIT
	}
}
