namespace BeanCounter
{
	public enum mg_bc_EResourceList
	{
		TITLE_ASSET_SOUNDS,
		GAME_ASSET_BACKGROUND,
		GAME_ASSET_GAME_LOGIC,
		GAME_ASSET_HAZARD,
		GAME_ASSET_BAG,
		GAME_ASSET_ONE_UP,
		GAME_ASSET_SHIELD,
		GAME_ASSET_OBJECT_SOUNDS,
		GAME_ASSET_SINGLE_SOUNDS,
		GAME_ASSET_GAME_SOUNDS
	}
}
